USE [master]
GO

/****** Object:  Database [mi_casa]    Script Date: 12/22/2015 04:39:20 ******/
CREATE DATABASE [mi_casa] ON  PRIMARY 
( NAME = N'mi_casa', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\mi_casa.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'mi_casa_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\mi_casa_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [mi_casa] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [mi_casa].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [mi_casa] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [mi_casa] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [mi_casa] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [mi_casa] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [mi_casa] SET ARITHABORT OFF 
GO

ALTER DATABASE [mi_casa] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [mi_casa] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [mi_casa] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [mi_casa] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [mi_casa] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [mi_casa] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [mi_casa] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [mi_casa] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [mi_casa] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [mi_casa] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [mi_casa] SET  DISABLE_BROKER 
GO

ALTER DATABASE [mi_casa] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [mi_casa] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [mi_casa] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [mi_casa] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [mi_casa] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [mi_casa] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [mi_casa] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [mi_casa] SET  READ_WRITE 
GO

ALTER DATABASE [mi_casa] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [mi_casa] SET  MULTI_USER 
GO

ALTER DATABASE [mi_casa] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [mi_casa] SET DB_CHAINING OFF 
GO

